# Potencial Talents

This apparently requires a unsupervised ranking

## Importing Dependencies

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report, average_precision_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

print('Modules Imported')

Modules Imported

## Import Data

In [2]:
data_path = 'potential-talents.xlsx'

In [3]:
data = pd.read_excel(data_path)

data

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,NaN
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500+,NaN
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,NaN
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,NaN
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,NaN
...,...,...,...,...,...
99,100,Aspiring Human Resources Manager | Graduating ...,"Cape Girardeau, Missouri",103,NaN
100,101,Human Resources Generalist at Loparex,"Raleigh-Durham, North Carolina Area",500+,NaN
101,102,Business Intelligence and Analytics at Travelers,Greater New York City Area,49,NaN
102,103,Always set them up for Success,Greater Los Angeles Area,500+,NaN
103,104,Director Of Administration at Excellence Logging,"Katy, Texas",500+,NaN

## Exploring Dataset

**X:**

- `id`: unique identifier for candidate (numeric)
- `job_title`: job title for candidate (text)
- `location`: geographical location for candidate (text)
- `connections`: number of connections candidate has, 500+ means over 500 (text)

**Y:**

- `fit`: how fit the candidate is for the role? (numeric, probability between 0-1)

In [4]:
keywords = ['Aspiring human resources','seeking human resources']

The words that will be used for semantic search

In [5]:
job_titles = data['job_title']

job_titles

0      2019 C.T. Bauer College of Business Graduate (...
1      Native English Teacher at EPIK (English Progra...
2                  Aspiring Human Resources Professional
3                 People Development Coordinator at Ryan
4        Advisory Board Member at Celal Bayar University
                             ...
99     Aspiring Human Resources Manager | Graduating ...
100                Human Resources Generalist at Loparex
101     Business Intelligence and Analytics at Travelers
102                       Always set them up for Success
103     Director Of Administration at Excellence Logging
Name: job_title, Length: 104, dtype: object

Fetching job titles from the dataframe

In [6]:
vectorizer = TfidfVectorizer()

# Creating matrix based on the vectorization of the job titles
job_titles_matrix = vectorizer.fit_transform(job_titles)

# Creating matrix based on the vectorization of the keywords
keywords_matrix = vectorizer.transform(keywords)

In [18]:
# Geting a matrix with the similarity score from comparing the job titles with the keywords
resulting_matrix = cosine_similarity(job_titles_matrix, keywords_matrix)

# Getting the sum score of all tokens from each candidate
#resulting_matrix = resulting_matrix.sum(axis=1)

# Getting the mean score of all tokens from each candidate
#resulting_matrix = resulting_matrix.mean(axis=1)

# Getting the max score of all tokens from each candidate
resulting_matrix = resulting_matrix.max(axis=1)

resulting_matrix

array([0.26531227, 0.        , 0.753591  , 0.        , 0.        ,
       0.69567872, 0.40060921, 0.        , 0.40060921, 0.46581385,
       0.        , 0.        , 0.18946052, 0.26531227, 0.26531227,
       0.        , 0.753591  , 0.        , 0.26531227, 0.        ,
       0.753591  , 0.        , 0.        , 0.69567872, 0.40060921,
       0.        , 0.42408409, 0.66493323, 0.42408409, 0.66493323,
       0.26531227, 0.        , 0.753591  , 0.        , 0.        ,
       0.69567872, 0.40060921, 0.        , 0.40060921, 0.46581385,
       0.        , 0.        , 0.18946052, 0.26531227, 0.        ,
       0.753591  , 0.        , 0.        , 0.69567872, 0.40060921,
       0.        , 0.40060921, 0.46581385, 0.        , 0.        ,
       0.18946052, 0.26531227, 0.753591  , 0.        , 0.69567872,
       0.        , 0.46581385, 0.        , 0.        , 0.18946052,
       0.33596153, 0.19758021, 0.24007198, 0.13984911, 0.25320642,
       0.1920007 , 0.35981638, 0.57364362, 0.46015863, 0.23711439,
       0.18781711, 0.10824288, 0.24257007, 0.29767933, 0.        ,
       0.15165424, 0.26172354, 0.        , 0.12734654, 0.        ,
       0.        , 0.        , 0.25753129, 0.21863268, 0.        ,
       0.        , 0.1643098 , 0.        , 0.31665961, 0.        ,
       0.        , 0.753591  , 0.        , 0.64485098, 0.30359897,
       0.24257007, 0.        , 0.        , 0.        ])

In [19]:
# Adding the score data to the fit column
data = data.assign(fit=resulting_matrix)

data

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.265312
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500+,0.000000
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.753591
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,0.000000
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,0.000000
...,...,...,...,...,...
99,100,Aspiring Human Resources Manager | Graduating ...,"Cape Girardeau, Missouri",103,0.303599
100,101,Human Resources Generalist at Loparex,"Raleigh-Durham, North Carolina Area",500+,0.242570
101,102,Business Intelligence and Analytics at Travelers,Greater New York City Area,49,0.000000
102,103,Always set them up for Success,Greater Los Angeles Area,500+,0.000000
103,104,Director Of Administration at Excellence Logging,"Katy, Texas",500+,0.000000

In [20]:
data.head()

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.265312
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500+,0.000000
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.753591
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,0.000000
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,0.000000

In [21]:
sorted_fit_data = data.sort_values(by=['fit'], ascending=False)

In [22]:
sorted_fit_data.head(50)

,id,job_title,location,connection,fit
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.753591
32,33,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.753591
16,17,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.753591
20,21,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.753591
57,58,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.753591
96,97,Aspiring Human Resources Professional,"Kokomo, Indiana Area",71,0.753591
45,46,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.753591
23,24,Aspiring Human Resources Specialist,Greater New York City Area,1,0.695679
59,60,Aspiring Human Resources Specialist,Greater New York City Area,1,0.695679
5,6,Aspiring Human Resources Specialist,Greater New York City Area,1,0.695679
35,36,Aspiring Human Resources Specialist,Greater New York City Area,1,0.695679
48,49,Aspiring Human Resources Specialist,Greater New York City Area,1,0.695679
29,30,Seeking Human Resources Opportunities,"Chicago, Illinois",390,0.664933
27,28,Seeking Human Resources Opportunities,"Chicago, Illinois",390,0.664933
98,99,Seeking Human Resources Position,"Las Vegas, Nevada Area",48,0.644851
72,73,"Aspiring Human Resources Manager, seeking inte...","Houston, Texas Area",7,0.573644
52,53,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.465814
9,10,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.465814
39,40,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.465814
61,62,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.465814
73,74,Human Resources Professional,Greater Boston Area,16,0.460159
28,29,Aspiring Human Resources Management student se...,"Houston, Texas Area",500+,0.424084
26,27,Aspiring Human Resources Management student se...,"Houston, Texas Area",500+,0.424084
6,7,Student at Humber College and Aspiring Human R...,Kanada,61,0.400609
36,37,Student at Humber College and Aspiring Human R...,Kanada,61,0.400609
38,39,Student at Humber College and Aspiring Human R...,Kanada,61,0.400609
8,9,Student at Humber College and Aspiring Human R...,Kanada,61,0.400609
24,25,Student at Humber College and Aspiring Human R...,Kanada,61,0.400609
51,52,Student at Humber College and Aspiring Human R...,Kanada,61,0.400609
49,50,Student at Humber College and Aspiring Human R...,Kanada,61,0.400609
71,72,Business Management Major and Aspiring Human R...,"Monroe, Louisiana Area",5,0.359816
65,66,Experienced Retail Manager and aspiring Human ...,"Austin, Texas Area",57,0.335962
93,94,Seeking Human Resources Opportunities. Open t...,Amerika Birleşik Devletleri,415,0.316660
99,100,Aspiring Human Resources Manager | Graduating ...,"Cape Girardeau, Missouri",103,0.303599
78,79,Liberal Arts Major. Aspiring Human Resources A...,"Baton Rouge, Louisiana Area",7,0.297679
13,14,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.265312
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.265312
14,15,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.265312
30,31,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.265312
18,19,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.265312
43,44,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.265312
56,57,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.265312
81,82,Aspiring Human Resources Professional | An ene...,"Austin, Texas Area",174,0.261724
87,88,Human Resources Management Major,"Milpitas, California",18,0.257531
69,70,"Retired Army National Guard Recruiter, office ...","Virginia Beach, Virginia",82,0.253206
77,78,Human Resources Generalist at Schwan's,Amerika Birleşik Devletleri,500+,0.242570
100,101,Human Resources Generalist at Loparex,"Raleigh-Durham, North Carolina Area",500+,0.242570
67,68,Human Resources Specialist at Luxottica,Greater New York City Area,500+,0.240072
74,75,"Nortia Staffing is seeking Human Resources, Pa...","San Jose, California",500+,0.237114
88,89,Director Human Resources at EY,Greater Atlanta Area,349,0.218633